Remove Test Cases from Search Result and New Search bar where they could be searched
OpenGenus/cosmos-search pull request #78
Opened 2018-03-02 09:50 UTC by pragyach

**Checklist**

- [x] My branch is up-to-date with the upstream `develop` branch.
- [x] I have added necessary documentation (if appropriate).

**Which issue does this PR fix?**: 
fixes: #67

**Why do we need this PR?**:

This pr completely solves issue#67.Test cases are removed from main search engine.Second search bar is enabled for handling these testing algorithms so they do not go waste.

**Demo (optional)**:
Before:-
![cs97](https://user-images.githubusercontent.com/20520778/36893065-bc92cc14-1e2c-11e8-9e04-b2abbeb1be11.png)
After:-When test is typed in first  search bar i.e. main search bar.
![_test_ _ cosmos-search](https://user-images.githubusercontent.com/20520778/36893182-14758d54-1e2d-11e8-814c-5f3fa50c30eb.png)
When test is typed in second search bar
![__ _ cosmos-search](https://user-images.githubusercontent.com/20520778/36893209-28da4500-1e2d-11e8-9811-1837cfab9c0c.png)

**Testing instructions:**

If there is any work still left to do, please add it here.

**TODOs (if any)**:

2018-03-02 14:34 UTC, soc221b requested changes
The codes of newer commit have overridden.

2018-03-02 14:34 UTC, iattempt commented on search/views.py
> -# Search strategy
Some codes of newer commit have overridden.

2018-03-02 14:34 UTC, iattempt commented on search/views.py
> -    return render(request, 'cosmos/index.html', {'algo_name': algo_tag})
Same here.

2018-03-02 14:34 UTC, iattempt commented on search/views.py
> -
And other newer support for Ajax.

2018-03-02 14:43 UTC, soc221b requested changes

2018-03-02 14:43 UTC, iattempt commented on search/views.py
> +    return algo_tag1
What is different between `searchbar()` and `searchbar1()`?

2018-03-02 14:43 UTC, iattempt commented on search/views.py
> +    return render(request, 'cosmos/error/HTTP500.html')
These function is duplicate.

2018-03-02 14:43 UTC, iattempt commented on search/views.py
> +def query1(request):
Should be readable and meaningful.

2018-03-04 15:52 UTC, AdiChat commented
Nice work :+1: 

Having two search bars will confuse users.

Ideally, users may not search for test files and might want to go to particular implementations. That being said, we can associate test files with respective codes and display them when the codes are displayed within Cosmos Search (a future feature). 
Associating test files will give users additional insights into the various possible test case scenarios for the particular algorithm.

2024-03-23 09:21 UTC, closed without merging